### ISSUE TITLE
The example in MLeap-Spark documentation dose not work

### ISSUE THREAD

**Issue by lu-wang-dl** [combust/mleap-docs#13]
I followed the example on [mleap doc](http://mleap-docs.combust.ml/spark/) serialize and deserialize the spark model. It does not work. 

It seems that the way on the doc as following is not the right way to do the serialization.
```
for(bundle <- managed(BundleFile("jar:file:/tmp/mleap-examples/simple-json.zip"))) {
  pipeline.writeBundle.format(SerializationFormat.Json).save(bundle)
}
```
The way to serialize the model I did is with "SparkBundleContext".
```
implicit val context = SparkBundleContext().withDataset(sparkTransformed)

for(modelFile <- managed(BundleFile("jar:file:/tmp/mleap-examples/simple-json.zip"))) {
model.writeBundle.save(modelFile)(context)
}
```

Am I doing something wrong or the documentation is not correct?

**Comment by ancasarb** [comment]
Thank you for the documentation issue report, I've updated the example in this PR #17.
