### ISSUE TITLE
Create custom transformers using pyspark

### ISSUE THREAD

**Issue by somya12** [combust/mleap-docs#15]
Hi,

Is it possible to create custom transformers in pyspark using mleap?  This [doc](https://github.com/combust/mleap-docs/blob/master/faq.md) states that the pyspark support is yet to come. On the other hand, the [pyspark](https://github.com/combust/mleap-docs/blob/master/py-spark/index.md) documentation states that the support is already present. If custom transformers are support, can someone direct me to a few examples?

**Comment by danjump** [comment]
I'd just like to follow up on this same point - I'd also like to create a custom mleap transformer from python code.

 I too read [here](https://github.com/combust/mleap-docs/blob/master/faq.md#why-use-mleap-bundles-and-not-pmml-or-other-serialization-frameworks) where it says custom transformers in python and C are on their way. Is there any place we can go to track the status of this work in more detail?

**Comment by ancasarb** [comment]
Please follow https://github.com/combust/mleap/issues/570 for the latest developments on this issue.
