### ISSUE TITLE
TypeError: serialize_to_bundle() missing 1 required positional argument: 'model_name'

### ISSUE THREAD

**Issue by SheldonGrant** [combust/mleap-docs#19]
in serialize_to_bundle(self, path, model_name, init)
     27 def serialize_to_bundle(self, path, model_name, init=False):
     28     serializer = SimpleSerializer()
     29     serializer.serialize_to_bundle(self, path, model_name, init)

Above there seems to be an issue with how serializer.serialize_to_bundle() is called here with serialize_to_bundel() class method.
* To many passed parameters here. The self param was left in the method call. Would this not be the appropriate call instead?
* a new Simple Serializer is instantiated here, therefore, the self is not valid here.

def serialize_to_bundle(self, path, model_name, init=False):
     28     serializer = SimpleSerializer() # instantiation of new Simple Serializer
     29     serializer.serialize_to_bundle(path, model_name, init) #without self.

**Comment by ancasarb** [comment]
@SheldonGrant what example are you trying to follow? thank you!

**Comment by ancasarb** [comment]
Closing, please re-open if this is still an issue. Thank you!
